### ISSUE TITLE
JSON device descriptor naming

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Nod#3]
It looks like there's no JSON device descriptor in the master branch, just a sample config file. The plugin will not work properly, and I can't add it to the aggregator, until one is available. I thought for sure there was one, because I am pretty sure I remember code-reviewing one...

**Comment by gfrolov** [comment]
Looks like it was moved from root to the /Plugin directory

**Comment by rpavlik** [comment]
Should be named to match the plugin name - that is, the reverse-domain-name.

**Comment by Khwaab** [comment]
Interesting, it worked on my setup without the name matching, anyway submitted a pull request to change the name

**Comment by rpavlik** [comment]
Well, it's not required, but it's good practice, particularly since we now have out-of-band processing of static descriptors for web display: https://github.com/OSVR/OSVR-Compatibility-Aggregator/blob/master/lib/osvr_compatibility_aggregator/device_descriptors.rb

**Comment by Khwaab** [comment]
ah interesting, would you like me to rename the plugin to something like com_osvr_NodPlugin?

**Comment by Khwaab** [comment]
can we close this with my pull request?

**Comment by gfrolov** [comment]
Closing this issue, there is a pull request opened to rename it #5
